run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - gofumpt
    - revive

linters-settings:
  gocyclo:
    min-complexity: 25

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - emptyStringTest

  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input

  goconst:
    min-len: 5
    min-occurrences: 5

  unparam:
    check-exported: false

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unparam

    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

    # Exclude shadow checking on err variables
    - linters:
        - govet
      text: 'shadow: declaration of "err"'

    # Exclude specific unparam issues for methods that always return nil
    - linters:
        - unparam
      text: "result 1 \\(error\\) is always nil"

    # Exclude goconst for file extensions
    - linters:
        - goconst
      text: "string `\\.eml` has .* occurrences"

  max-issues-per-linter: 0
  max-same-issues: 0
